CREATE TABLE LOG (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    APPLICATION VARCHAR (50) NOT NULL,
    LOGGED_DATE DATE NOT NULL,
    LEVEL_TEXT VARCHAR (50) NOT NULL,
    USER_TEXT VARCHAR (250) NOT NULL,
    MESSAGE VARCHAR (800) NOT NULL,
    LOGGER VARCHAR (250) NULL,
    CALLSITE VARCHAR (800) NULL,
    EXCEPTION_TEXT VARCHAR (800) NULL,
    PRIMARY KEY (ID)
);
