CREATE TABLE EMPLOYEE (
    ID VARCHAR (50) NOT NULL,
    NAME VARCHAR (50) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    ADDRESS VARCHAR (255) NOT NULL,
    ENCRYPT_BIRTHDATE RAW(255) NOT NULL,
    ENCRYPT_ADDRESS RAW(255) NOT NULL,
    PRIMARY KEY (ID)
);